apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: wondr-desktop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wondr-desktop-frontend
  template:
    metadata:
      labels:
        app: wondr-desktop-frontend
    spec:
      containers:
      - name: frontend-container
        image: asia.gcr.io/primeval-rune-467212-t9/wondr-desktop-fe:latest
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"