apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: wondr-desktop-db
spec:
  type: ClusterIP
  selector:
    app: wondr-desktop-db
  ports:
    - protocol: TCP
      port: 5432 
      targetPort: 5432 