apiVersion: apps/v1
kind: Deployment
metadata:
  name: wondr-desktop-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wondr-desktop-backend
  template:
    metadata:
      labels:
        app: wondr-desktop-backend
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.36.1
        command: ['sh', '-c', 'until nc -z postgresql-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
      - name: backend-container
        image: asia.gcr.io/primeval-rune-467212-t9/wondr-desktop-be:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-credentials
        env:
          # Pastikan Anda menggunakan nama variabel lingkungan yang sama dengan yang ada di application.properties
          - name: DB_URL
            value: "jdbc:postgresql://postgresql-service:5432/${POSTGRES_DB}"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: database