apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: wondr-desktop-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080