apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wondr-desktop-backend
  template:
    metadata:
      labels:
        app: wondr-desktop-backend
    spec:
      containers:
      - name: backend-container
        image: asia.gcr.io/primeval-rune-467212-t9/wondr-desktop-be:latest
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: backend-config
        # - secretRef:
        #     name: postgres-credentials
        - secretRef:
            name: app-secrets
        env: 
        - name: FIREBASE_CONFIG_PATH
          # value: model-parsec-465503-p3-firebase-adminsdk-fbsvc-1e9901efad.json
          value: wondr-desktop-otp-firebase-adminsdk-fbsvc-779cc379ef.json
        - name: DB_HOST
          value: postgresql-service.backend
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password