apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  # type: LoadBalancer
  type: ClusterIP
  selector:
    app: wondr-desktop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80